### ISSUE TITLE
Style <code> elements in headers

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidytemplate#21]
e.g.  The font-size for `h3` is 1.6em, but `<code>` elements get sized to 14px. Matching the h3 font-size looks *huge* in the code font. My recommended CSS would be:
```CSS
h3 code {
    font-size: 1em;
}
```
