### ISSUE TITLE
part_of param should allow links

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidytemplate#34]
Currently, I don't think that I can include a link to the `tidymodels` github page in `_pkgdown.yml` like this:

```
template:
  package: tidytemplate
  params:
    part_of: <a href="https://github.com/tidymodels">tidymodels</a>
    # or this
    part_of: [tidymodels](https://github.com/tidymodels)
```

I don't know a ton about yaml/html interaction, but it seems like you can prevent html escaping by using triple braces? i.e. `{{{part_of}}}`.
https://github.com/tidyverse/tidytemplate/blob/master/inst/pkgdown/templates/navbar.html#L15

That at least let me do the first `part_of` option above. If there are other easier solutions that would be nice too. I probably would want to include a link in the `footer` too.
